info:
  component: eureka-service

spring:
  application:
    name: eureka-service

server:
  port: 8081

eureka:
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
