#Component Info
info:
  component: discovery-service

#Spring Application Name 
spring:
  application:
    name: discovery-service

# HTTP Server
server:
  port: 8081

# Eureka Configuration Properties
eureka:
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0